module.exports = {
  amountParam: 'tp_amount',
  currencyParam: 'tp_currency',
  descriptionParam: 'tp_description',
  messageParam: 'tp_message',
  transactionIdParam: 'tp_transaction_id',
  orderIdParam: 'tp_merchant_order_id',
  redirectUrlParam: 'tp_redirect_url',
  statusParam: 'tp_transaction_status',
  transactionNumberParam: 'tp_transaction_number',
  userIdParam: 'tp_merchant_user_id',
  verificationTokenParam: 'tendopay_verification_token',
  billingCityParam: 'tp_billing_city',
  billingAddress1Param: 'tp_billing_address1',
  billingPostcodeParam: 'tp_billing_postcode',
  shippingCityParam: 'tp_shipping_city',
  shippingAddress1Param: 'tp_shipping_address1',
  shippingPostcodeParam: 'tp_shipping_postcode',
  orderTokenParam: 'tp_order_token',
  authorizeUrlParam: 'tp_authorize_url',
  xSignatureParam: 'x_signature'
};
